import { Data, IproductInput } from "@/types";


const products: IproductInput[] = [
    // --- PAPERBAGS (7 Items) ---
    {
        name: "Classic Brown Kraft Paper Bag",
        slug: "classic-brown-kraft-paper-bag",
        category: "Paperbags",
        images: ["https://placehold.co/600x600/d2b48c/ffffff?text=Brown+Kraft+Bag", "https://placehold.co/600x600/d2b48c/ffffff?text=Brown+Kraft+Bag+2, https://placehold.co/600x600/d2b48c/ffffff?text=Brown+Kraft+Bag+3"],
        description: "Durable, eco-friendly brown kraft paper bags with twisted handles. Perfect for retail and gifts.",
        price: 12.99,
        listPrice: 15.99,
        isPublished: true,
        countInStock: 4,
        tags: ["eco-friendly", "retail", "best-seller"],    
        sizes: ["Small", "Medium", "Large"],
        colors: ["Brown"],
        dimensions: { width: 10, height: 15, depth: 5 },
        avgRating: 4.5,
        numReviews: 182,
        ratingDistribution: [
            { rating: 5, count: 120 },
            { rating: 4, count: 45 },
            { rating: 3, count: 10 },
            { rating: 2, count: 5 },
            { rating: 1, count: 2 }
        ],
        numSales: 300,
        reviews: []
    },
    {
        name: "White Cardboard Boutique Bag",
        slug: "white-cardboard-boutique-bag",
        category: "Paperbags",
        images: ["https://placehold.co/600x600/ffffff/000000?text=White+Boutique+Bag", "https://placehold.co/600x600/ffffff/000000?text=White+Boutique+Bag+2"],
        description: "Premium white cardboard bags with rope handles. Ideal for high-end clothing and boutiques.",
        price: 24.50,
        listPrice: 29.99,
        isPublished: true,
        countInStock: 8,
        tags: ["luxury", "boutique", "white", "today-deal"],
        sizes: ["Medium", "Large"],
        colors: ["White"],
        dimensions: { width: 12, height: 16, depth: 6 },
        avgRating: 4.8,
        numReviews: 48,
        ratingDistribution: [
            { rating: 5, count: 40 },
            { rating: 4, count: 6 },
            { rating: 3, count: 1 },
            { rating: 2, count: 0 },
            { rating: 1, count: 1 }
        ],
        numSales: 120,
        reviews: []
    },
    {
        name: "Recycled Green Grocery Paper Bag",
        slug: "recycled-green-grocery-bag",
        category: "Paperbags",
        images: ["https://placehold.co/600x600/2e8b57/ffffff?text=Green+Grocery+Bag", "https://placehold.co/600x600/2e8b57/ffffff?text=Green+Grocery+Bag+2"],
        description: "Heavy-duty paper bags made from 100% recycled materials. Flat bottom for easy packing.",
        price: 8.99,
        listPrice: 12.99,
        isPublished: true,
        countInStock: 5,
        tags: ["recycled", "grocery"],
        sizes: ["Standard"],
        colors: ["Green", "Brown"],
        dimensions: { width: 12, height: 17, depth: 7 },
        avgRating: 4.2,
        numReviews: 76,
        ratingDistribution: [
            { rating: 5, count: 40 },
            { rating: 4, count: 20 },
            { rating: 3, count: 10 },
            { rating: 2, count: 4 },
            { rating: 1, count: 2 }
        ],
        numSales: 50,
        reviews: []
    },
    {
        name: "Party Patterned Paper Bag",
        slug: "party-patterned-paper-bag",
        category: "Paperbags",
        images: ["https://placehold.co/600x600/ff69b4/ffffff?text=Party+Bag", "https://placehold.co/600x600/ff69b4/ffffff?text=Party+Bag+2"],
        description: "Fun and colorful patterned bags for birthdays and events. Comes in a pack of 12.",
        price: 5.99,
        listPrice: 7.99,
        isPublished: true,
        countInStock: 2,
        tags: ["party", "events", "colorful"],
        sizes: ["Small"],
        colors: ["Pink", "Blue", "Yellow"],
        dimensions: { width: 6, height: 8, depth: 3 },
        avgRating: 4.5,
        numReviews: 240,
        ratingDistribution: [
            { rating: 5, count: 160 },
            { rating: 4, count: 50 },
            { rating: 3, count: 20 },
            { rating: 2, count: 6 },
            { rating: 1, count: 4 }
        ],
        numSales: 600,
        reviews: []
    },
    {
        name: "Black Matte Laminate Bag",
        slug: "black-matte-laminate-bag",
        category: "Paperbags",
        images: ["https://placehold.co/600x600/000000/ffffff?text=Black+Matte+Bag"],
        description: "Sophisticated black matte finish with matching handles. Excellent for corporate gifting.",
        price: 29.99,
        listPrice: 35.00,
        isPublished: true,
        countInStock: 6,
        tags: ["corporate", "luxury", "black"],
        sizes: ["Medium"],
        colors: ["Black"],
        dimensions: { width: 10, height: 12, depth: 4 },
        avgRating: 4.6,
        numReviews: 120,
        ratingDistribution: [
            { rating: 5, count: 90 },
            { rating: 4, count: 20 },
            { rating: 3, count: 5 },
            { rating: 2, count: 3 },
            { rating: 1, count: 2 }
        ],
        numSales: 90,
        reviews: []
    },
    {
        name: "Flat Merchandise Paper Bag",
        slug: "flat-merchandise-paper-bag",
        category: "Paperbags",
        images: ["https://placehold.co/600x600/f5deb3/000000?text=Flat+Merch+Bag"],
        description: "Simple flat paper bags for postcards, greeting cards, and small accessories.",
        price: 4.50,
        listPrice: 6.99,
        isPublished: true,
        countInStock: 10,
        tags: ["stationery", "flat"],
        sizes: ["5x7", "8x10"],
        colors: ["Brown", "White"],
        dimensions: { width: 5, height: 7, depth: 0.1 },
        avgRating: 4.2,
        numReviews: 60,
        ratingDistribution: [
            { rating: 5, count: 30 },
            { rating: 4, count: 20 },
            { rating: 3, count: 6 },
            { rating: 2, count: 3 },
            { rating: 1, count: 1 }
        ],
        numSales: 400,
        reviews: []
    },
    {
        name: "Wine Bottle Paper Bag",
        slug: "wine-bottle-paper-bag",
        category: "Paperbags",
        images: ["https://placehold.co/600x600/800000/ffffff?text=Wine+Bag"],
        description: "Tall, slender bags specifically designed to hold standard wine bottles safely.",
        price: 18.00,
        listPrice: 22.99,
        isPublished: true,
        countInStock: 12,
        tags: ["wine", "gifts"],
        sizes: ["Standard"],
        colors: ["Red", "Black", "Gold"],
        dimensions: { width: 5, height: 15, depth: 4 },
        avgRating: 4.4,
        numReviews: 95,
        ratingDistribution: [
            { rating: 5, count: 60 },
            { rating: 4, count: 20 },
            { rating: 3, count: 7 },
            { rating: 2, count: 5 },
            { rating: 1, count: 3 }
        ],
        numSales: 210,
        reviews: []
    },

    // --- GIFT BOXES (7 Items) ---
    {
        name: "Premium Magnetic Closure Box",
        slug: "premium-magnetic-closure-box",
        category: "Gift Boxes",
        images: ["https://placehold.co/600x600/333333/ffffff?text=Magnetic+Box"],
        description: "Rigid box with a magnetic front flap. Ships flat and assembles in seconds.",
        price: 8.50,
        listPrice: 12.99,
        isPublished: true,
        countInStock: 3,
        tags: ["premium", "magnetic", "rigid"],
        sizes: ["Medium", "Large"],
        colors: ["Black", "White"],
        dimensions: { width: 10, height: 4, depth: 10 },
        avgRating: 4.6,
        numReviews: 420,
        ratingDistribution: [
            { rating: 5, count: 310 },
            { rating: 4, count: 70 },
            { rating: 3, count: 20 },
            { rating: 2, count: 10 },
            { rating: 1, count: 10 }
        ],
        numSales: 550,
        reviews: []
    },
    {
        name: "Square Jewelry Gift Box",
        slug: "square-jewelry-gift-box",
        category: "Gift Boxes",
        images: ["https://placehold.co/600x600/ffdab9/000000?text=Jewelry+Box"],
        description: "Small square box with cotton insert, perfect for rings, earrings, and pendants.",
        price: 2.99,
        listPrice: 4.99,
        isPublished: true,
        countInStock: 8,
        tags: ["jewelry", "small", "today-deal"],
        sizes: ["2x2", "3x3"],
        colors: ["Peach", "Teal", "White"],
        dimensions: { width: 3, height: 1.5, depth: 3 },
        avgRating: 4.4,
        numReviews: 140,
        ratingDistribution: [
            { rating: 5, count: 90 },
            { rating: 4, count: 30 },
            { rating: 3, count: 10 },
            { rating: 2, count: 6 },
            { rating: 1, count: 4 }
        ],
        numSales: 1200,
        reviews: []
    },
    {
        name: "Corrugated Mailer Box",
        slug: "corrugated-mailer-box",
        category: "Gift Boxes",
        images: ["https://placehold.co/600x600/8b4513/ffffff?text=Mailer+Box"],
        description: "Sturdy corrugated cardboard mailer, great for subscription boxes and shipping.",
        price: 1.50,
        listPrice: 2.99,
        isPublished: true,
        countInStock: 20,
        tags: ["shipping", "mailer", "sturdy"],
        sizes: ["6x4x2", "10x8x4"],
        colors: ["Kraft", "White"],
        dimensions: { width: 10, height: 4, depth: 8 },
        avgRating: 4.6,
        numReviews: 1200,
        ratingDistribution: [
            { rating: 5, count: 900 },
            { rating: 4, count: 200 },
            { rating: 3, count: 60 },
            { rating: 2, count: 25 },
            { rating: 1, count: 15 }
        ],
        numSales: 5000,
        reviews: []
    },
    {
        name: "Clear Window Treat Box",
        slug: "clear-window-treat-box",
        category: "Gift Boxes",
        images: ["https://placehold.co/600x600/ffffff/ff0000?text=Window+Box"],
        description: "Bakery style box with a clear window to display cookies, cupcakes, or gifts.",
        price: 12.00,
        listPrice: 15.99,
        isPublished: true,
        countInStock: 4,
        tags: ["bakery", "display", "window"],
        sizes: ["Medium"],
        colors: ["White", "Kraft"],
        dimensions: { width: 8, height: 3, depth: 8 },
        avgRating: 4.5,
        numReviews: 240,
        ratingDistribution: [
            { rating: 5, count: 160 },
            { rating: 4, count: 50 },
            { rating: 3, count: 20 },
            { rating: 2, count: 6 },
            { rating: 1, count: 4 }
        ],
        numSales: 320,
        reviews: []
    },
    {
        name: "Pillow Favor Box",
        slug: "pillow-favor-box",
        category: "Gift Boxes",
        images: ["https://placehold.co/600x600/c0c0c0/000000?text=Pillow+Box"],
        description: "Elegant pillow-shaped boxes for wedding favors or small candies.",
        price: 10.99,
        listPrice: 14.99,
        isPublished: true,
        countInStock: 6,
        tags: ["wedding", "favors", "elegant"],
        sizes: ["Small"],
        colors: ["Silver", "Gold"],
        dimensions: { width: 4, height: 1, depth: 3 },
        avgRating: 4.37,
        numReviews: 180,
        ratingDistribution: [
            { rating: 5, count: 110 },
            { rating: 4, count: 40 },
            { rating: 3, count: 20 },
            { rating: 2, count: 6 },
            { rating: 1, count: 4 }
        ],
        numSales: 800,
        reviews: []
    },
    {
        name: "Large Apparel Gift Box",
        slug: "large-apparel-gift-box",
        category: "Gift Boxes",
        images: ["https://placehold.co/600x600/f0f8ff/000000?text=Apparel+Box"],
        description: "Two-piece folding box designed for shirts, sweaters, and larger garments.",
        price: 18.50,
        listPrice: 22.99,
        isPublished: true,
        countInStock: 15,
        tags: ["clothing", "apparel", "today-deal"],
        sizes: ["Large"],
        colors: ["White"],
        dimensions: { width: 15, height: 2, depth: 11 },
        avgRating: 4.18,
        numReviews: 90,
        ratingDistribution: [
            { rating: 5, count: 50 },
            { rating: 4, count: 20 },
            { rating: 3, count: 10 },
            { rating: 2, count: 6 },
            { rating: 1, count: 4 }
        ],
        numSales: 90,
        reviews: []
    },
    {
        name: "Round Hat Box Set",
        slug: "round-hat-box-set",
        category: "Gift Boxes",
        images: ["https://placehold.co/600x600/ffb6c1/000000?text=Hat+Box"],
        description: "Set of nesting round boxes with lids. Beautiful for flower arrangements or storage.",
        price: 45.00,
        listPrice: 49.99,
        isPublished: true,
        countInStock: 4,
        tags: ["floral", "storage", "decorative"],
        sizes: ["Set of 3"],
        colors: ["Pink", "Cream"],
        dimensions: { width: 12, height: 12, depth: 12 },
        avgRating: 4.7,
        numReviews: 30,
        ratingDistribution: [
            { rating: 5, count: 24 },
            { rating: 4, count: 4 },
            { rating: 3, count: 1 },
            { rating: 2, count: 1 },
            { rating: 1, count: 0 }
        ],
        numSales: 25,
        reviews: []
    },

    // --- PLASTIC BAGS (6 Items) ---
    {
        name: "Frosted Die-Cut Handle Bag",
        slug: "frosted-die-cut-handle-bag",
        category: "Plastic Bags",
        images: ["https://placehold.co/600x600/e6e6fa/000000?text=Frosted+Bag"],
        description: "Semi-transparent frosted plastic bags with reinforced die-cut handles.",
        price: 15.00,
        isPublished: true,
        countInStock: 10,
        tags: ["retail", "frosted", "durable"],
        sizes: ["9x12", "12x15"],
        colors: ["Clear", "Blue", "Pink"],
        dimensions: { width: 9, height: 12, depth: 0.1 },
        avgRating: 4.4,
        numReviews: 320,
        ratingDistribution: [
            { rating: 5, count: 200 },
            { rating: 4, count: 70 },
            { rating: 3, count: 30 },
            { rating: 2, count: 12 },
            { rating: 1, count: 8 }
        ],
        numSales: 900,
        reviews: []
    },
    {
        name: "T-Shirt Shopping Bag",
        slug: "t-shirt-shopping-bag",
        category: "Plastic Bags",
        images: ["https://placehold.co/600x600/ffffff/000000?text=T-Shirt+Bag"],
        description: "Standard grocery style t-shirt bags. Economical and strong.",
        price: 14.99,
        listPrice: 19.99,
        isPublished: true,
        countInStock: 5,
        tags: ["economy", "grocery", "bulk"],
        sizes: ["Standard"],
        colors: ["White"],
        dimensions: { width: 11, height: 20, depth: 6 },
        avgRating: 4.18,
        numReviews: 2400,
        ratingDistribution: [
            { rating: 5, count: 1200 },
            { rating: 4, count: 700 },
            { rating: 3, count: 300 },
            { rating: 2, count: 120 },
            { rating: 1, count: 80 }
        ],
        numSales: 10000,
        reviews: []
    },
    {
        name: "Resealable Clear Poly Bag",
        slug: "resealable-clear-poly-bag",
        category: "Plastic Bags",
        images: ["https://placehold.co/600x600/dcdcdc/000000?text=Zip+Lock+Bag"],
        description: "Clear polyethylene bags with a zip-lock seal. Ideal for small parts or food storage.",
        price: 9.50,
        isPublished: true,
        countInStock: 0,
        tags: ["storage", "zip-lock", "clear", "today-deal"],
        sizes: ["4x6", "6x9"],
        colors: ["Clear"],
        dimensions: { width: 6, height: 9, depth: 0.1 },
        avgRating: 4.5,
        numReviews: 540,
        ratingDistribution: [
            { rating: 5, count: 380 },
            { rating: 4, count: 90 },
            { rating: 3, count: 40 },
            { rating: 2, count: 20 },
            { rating: 1, count: 10 }
        ],
        numSales: 1500,
        reviews: []
    },
    {
        name: "Biodegradable Compost Bag",
        slug: "biodegradable-compost-bag",
        category: "Plastic Bags",
        images: ["https://placehold.co/600x600/90ee90/000000?text=Bio+Bag"],
        description: "Eco-friendly alternative to plastic. Certified compostable materials.",
        price: 19.99,
        isPublished: true,
        countInStock: 4,
        tags: ["eco-friendly", "compostable"],
        sizes: ["13 Gallon"],
        colors: ["Light Green"],
        dimensions: { width: 24, height: 30, depth: 0.1 },
        avgRating: 4.14,
        numReviews: 210,
        ratingDistribution: [
            { rating: 5, count: 110 },
            { rating: 4, count: 50 },
            { rating: 3, count: 30 },
            { rating: 2, count: 10 },
            { rating: 1, count: 10 }
        ],
        numSales: 200,
        reviews: []
    },
    {
        name: "Heavy Duty Courier Bag",
        slug: "heavy-duty-courier-bag",
        category: "Plastic Bags",
        images: ["https://placehold.co/600x600/808080/ffffff?text=Courier+Bag"],
        description: "Self-sealing shipping bags, waterproof and tear-resistant for e-commerce delivery.",
        price: 22.00,
        isPublished: true,
        countInStock: 15,
        tags: ["shipping", "mailing", "waterproof"],
        sizes: ["10x13"],
        colors: ["Grey", "White"],
        dimensions: { width: 10, height: 13, depth: 0.1 },
        avgRating: 4.7,
        numReviews: 1500,
        ratingDistribution: [
            { rating: 5, count: 1200 },
            { rating: 4, count: 200 },
            { rating: 3, count: 60 },
            { rating: 2, count: 25 },
            { rating: 1, count: 15 }
        ],
        numSales: 5000,
        reviews: []
    },
    {
        name: "Glossy Boutique Bag with Loop Handle",
        slug: "glossy-boutique-bag",
        category: "Plastic Bags",
        images: ["https://placehold.co/600x600/ff00ff/ffffff?text=Glossy+Bag"],
        description: "High-gloss plastic bag with soft loop handles. Very attractive for retail.",
        price: 28.00,
        isPublished: true,
        countInStock: 25,
        tags: ["glossy", "fashion", "retail", "today-deal"],
        sizes: ["16x18"],
        colors: ["Hot Pink", "Black"],
        dimensions: { width: 16, height: 18, depth: 4 },
        avgRating: 4.41,
        numReviews: 110,
        ratingDistribution: [
            { rating: 5, count: 70 },
            { rating: 4, count: 25 },
            { rating: 3, count: 8 },
            { rating: 2, count: 4 },
            { rating: 1, count: 3 }
        ],
        numSales: 180,
        reviews: []
    }
]

const data: Data = {
    headerMenus: [
        { name: "Home", href: '/' },
        { name: "Shop", href: '/shop' },
        { name: "Categories", href: '/shop/products' },
        { name: "Deals & Offers", href: '/shop/products?deals=true' },
        { name: "Browsing History", href: '/history' },
        // { name: "Customer Service", href: '/page/customer-service' },
        { name: "About Us", href: '/page/about-us' },
        { name: "Contact Us", href: '/page/contact-us' },
    ],
    carousels: [
        {
            title: "Paperbags 1",
            buttonCaption: "Shop Now",
            imageUrl: "/images/banner1.png", // Renamed from imageUrl to match index.ts
            href: "/products/slug-paperbags-1", // Fixed typo prodducts -> products
            isPublished: true
        },
        {
            title: "Paperbags 2",
            buttonCaption: "Shop Now",
            imageUrl: "/images/banner2.png", // Renamed from imageUrl to match index.ts
            href: "/products/slug-paperbags-2",
            isPublished: true
        }
    ],
    products
}

export default data;